{"uid":"6db31de235775672","name":"test_delete_vote","fullName":"tests.test_votes#test_delete_vote","historyId":"22cb757286d599571786b8a79a9987bc","time":{"start":1759144338486,"stop":1759144338903,"duration":417},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_vote> (2 sub-exceptions)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 344, in from_call\n  |     result: TResult | None = func()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 246, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/logging.py\", line 858, in pytest_runtest_teardown\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/capture.py\", line 905, in pytest_runtest_teardown\n  |     return (yield)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 193, in pytest_runtest_teardown\n  |     item.session._setupstate.teardown_exact(nextitem)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 557, in teardown_exact\n  |     raise exceptions[0]\n  | exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_vote> (2 sub-exceptions)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    |     user_client.delete_image(image_id=get_image_response[0]['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    |     return self._request(\"DELETE\", f\"images/{image_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/bob\n    +---------------- 2 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 35, in vote_testdata\n    |     user_client.delete_vote(vote_id=post_vote_response['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 26, in delete_vote\n    |     return self._request(\"DELETE\", f\"votes/{vote_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thecatapi.com/v1/votes/1324337\n    +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"user_client","time":{"start":1759144322433,"stop":1759144322433,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"image_testdata","time":{"start":1759144337651,"stop":1759144337972,"duration":321},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"vote_testdata","time":{"start":1759144337972,"stop":1759144338486,"duration":514},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_vote> (2 sub-exceptions)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 344, in from_call\n  |     result: TResult | None = func()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 246, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/logging.py\", line 858, in pytest_runtest_teardown\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/capture.py\", line 905, in pytest_runtest_teardown\n  |     return (yield)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 193, in pytest_runtest_teardown\n  |     item.session._setupstate.teardown_exact(nextitem)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 557, in teardown_exact\n  |     raise exceptions[0]\n  | exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_vote> (2 sub-exceptions)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    |     user_client.delete_image(image_id=get_image_response[0]['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    |     return self._request(\"DELETE\", f\"images/{image_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/bob\n    +---------------- 2 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 35, in vote_testdata\n    |     user_client.delete_vote(vote_id=post_vote_response['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 26, in delete_vote\n    |     return self._request(\"DELETE\", f\"votes/{vote_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thecatapi.com/v1/votes/1324337\n    +------------------------------------","steps":[],"attachments":[{"uid":"dca41e1c0eb21454","name":"stdout","source":"dca41e1c0eb21454.txt","type":"text/plain","size":67}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"vote_testdata::0","time":{"start":1759144338904,"stop":1759144339193,"duration":289},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thecatapi.com/v1/votes/1324337\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 35, in vote_testdata\n    user_client.delete_vote(vote_id=post_vote_response['id'])\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 26, in delete_vote\n    return self._request(\"DELETE\", f\"votes/{vote_id}\")\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    response.raise_for_status()\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"image_testdata::0","time":{"start":1759144339194,"stop":1759144339409,"duration":215},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/bob\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    user_client.delete_image(image_id=get_image_response[0]['id'])\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    return self._request(\"DELETE\", f\"images/{image_id}\")\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    response.raise_for_status()\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_votes"},{"name":"host","value":"runnervm3ublj"},{"name":"thread","value":"2182-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_votes"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"6db31de235775672.json","parameterValues":[]}