{"uid":"e999d165d4da0f81","name":"test_delete_favourite","fullName":"tests.test_favourites#test_delete_favourite","historyId":"00603d909d928540ed53506b9833cfaa","time":{"start":1759144328414,"stop":1759144328719,"duration":305},"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_favourite> (2 sub-exceptions)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 344, in from_call\n  |     result: TResult | None = func()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 246, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/logging.py\", line 858, in pytest_runtest_teardown\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/capture.py\", line 905, in pytest_runtest_teardown\n  |     return (yield)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 193, in pytest_runtest_teardown\n  |     item.session._setupstate.teardown_exact(nextitem)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 557, in teardown_exact\n  |     raise exceptions[0]\n  | exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_favourite> (2 sub-exceptions)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    |     user_client.delete_image(image_id=get_image_response[0]['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    |     return self._request(\"DELETE\", f\"images/{image_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/eh1\n    +---------------- 2 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 47, in favourite_testdata\n    |     user_client.delete_favourite(favourite_id=post_favourite_response['id'])\n    | AttributeError: 'UserApiClient' object has no attribute 'delete_favourite'. Did you mean: 'delete_favourites'?\n    +------------------------------------","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"user_client","time":{"start":1759144322433,"stop":1759144322433,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"image_testdata","time":{"start":1759144327820,"stop":1759144328142,"duration":322},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"favourite_testdata","time":{"start":1759144328143,"stop":1759144328414,"duration":271},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_favourite> (2 sub-exceptions)","statusTrace":"+ Exception Group Traceback (most recent call last):\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 344, in from_call\n  |     result: TResult | None = func()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 246, in <lambda>\n  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_hooks.py\", line 512, in __call__\n  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n  |     raise exception\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/logging.py\", line 858, in pytest_runtest_teardown\n  |     yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n  |     return result.get_result()\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_result.py\", line 103, in get_result\n  |     raise exc.with_traceback(tb)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n  |     res = yield\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 139, in _multicall\n  |     teardown.throw(exception)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/capture.py\", line 905, in pytest_runtest_teardown\n  |     return (yield)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 121, in _multicall\n  |     res = hook_impl.function(*args)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 193, in pytest_runtest_teardown\n  |     item.session._setupstate.teardown_exact(nextitem)\n  |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 557, in teardown_exact\n  |     raise exceptions[0]\n  | exceptiongroup.ExceptionGroup: errors while tearing down <Function test_delete_favourite> (2 sub-exceptions)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    |     user_client.delete_image(image_id=get_image_response[0]['id'])\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    |     return self._request(\"DELETE\", f\"images/{image_id}\")\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    |     response.raise_for_status()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    |     raise HTTPError(http_error_msg, response=self)\n    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/eh1\n    +---------------- 2 ----------------\n    | Traceback (most recent call last):\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/runner.py\", line 546, in teardown_exact\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1069, in finish\n    |     raise exceptions[0]\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1058, in finish\n    |     fin()\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    |     return self._fixture_function(*args, **kwargs)\n    |   File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    |     next(it)\n    |   File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 47, in favourite_testdata\n    |     user_client.delete_favourite(favourite_id=post_favourite_response['id'])\n    | AttributeError: 'UserApiClient' object has no attribute 'delete_favourite'. Did you mean: 'delete_favourites'?\n    +------------------------------------","steps":[],"attachments":[{"uid":"765731b1824cc53f","name":"stdout","source":"765731b1824cc53f.txt","type":"text/plain","size":74}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"favourite_testdata::0","time":{"start":1759144328720,"stop":1759144328720,"duration":0},"status":"broken","statusMessage":"AttributeError: 'UserApiClient' object has no attribute 'delete_favourite'. Did you mean: 'delete_favourites'?\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 47, in favourite_testdata\n    user_client.delete_favourite(favourite_id=post_favourite_response['id'])\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"image_testdata::0","time":{"start":1759144328721,"stop":1759144328934,"duration":213},"status":"broken","statusMessage":"requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.thecatapi.com/v1/images/eh1\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/tests/conftest.py\", line 22, in image_testdata\n    user_client.delete_image(image_id=get_image_response[0]['id'])\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/user_api_client.py\", line 47, in delete_image\n    return self._request(\"DELETE\", f\"images/{image_id}\")\n  File \"/home/runner/work/TheCatsTest/TheCatsTest/api_clients/base_api_client.py\", line 37, in _request\n    response.raise_for_status()\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/requests/models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_favourites"},{"name":"host","value":"runnervm3ublj"},{"name":"thread","value":"2182-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_favourites"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"e999d165d4da0f81.json","parameterValues":[]}